name: image_crop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.9
  image_picker: ^0.8.4+4
  flutter_luban: ^0.1.13
  uuid: ^3.0.5
  intl: ^0.17.0
  get: 4.6.1
  dio: ^4.0.6
  percent_indicator: ^4.0.0
  image_cropper: ^1.5.0
  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/image/

